### ISSUE TITLE
[Question] How to handle ads.txt

### ISSUE THREAD

**Issue by JosiahParry** [coatless-quarto/adsense#1]
On google adsense it seems required (or at least very strongly encouraged) to have an ads.txt does this plugin assist with that?

**Comment by coatless** [comment]
@JosiahParry great question. Since `ads.txt` is a standalone file that multiple ad vendors can request additions to, we're likely going to have another section inside of the installation instructions.

**Comment by coatless** [comment]
If you have time later today, feel free to check out the updated documentation entry: 

https://github.com/coatless-quarto/adsense/pull/2/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

Let me know if you have any other questions or suggestions!

**Comment by JosiahParry** [comment]
Thanks !!! I'll check it out soon

**Comment by JosiahParry** [comment]
Perfect! I say merge it. That's what I _thought_ we need to do but wasn't sure. Thanks for the quick turn around!!
